# Let's set our initial list of numbers that were "randomly" generated by "random.org"
list_a = [13, 8, 16, 10, 9, 12, 5, 3, 7, 6, 1, 15, 4, 18, 17, 20, 14, 2, 19, 11]

# Let's iterate through all the numbers in the initial list and find which ones are less than five and print them
for number in list_a:
    if number < 5:
        print(number)

# Instead of just printing out the numbers that are less than five, we will add them to a new list and print that out
list_b = []
for number in list_a:
    if number < 5:
        list_b.append(number)

# Now let's print the new list that contains only the numbers less than five
print(list_b)